# Generated by Django 6.1 on 2026-09-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_avance_maladie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
