# Generated by Django 6.1 on 2026-09-03 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvisionnement',
            name='avaries',
        ),
        migrations.RemoveField(
            model_name='approvisionnement',
            name='client',
        ),
        migrations.RemoveField(
            model_name='approvisionnement',
            name='prix_vente',
        ),
        migrations.CreateModel(
            name='Revente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avaries', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reventes', to='supply.approvisionnement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reventes', to='sales.client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
